name: Run on STAGE

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    environment: STAGE   # Use the STAGE environment secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Selenium Tests
        run: |
          echo "Running tests on STAGE"
          mvn clean test -Denv=STAGE
