name: Selenium Test Execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: STAGE
        type: choice
        options:
          - STAGE
          - KAOS
          - RP2

jobs:
  test:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Selenium Tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: mvn clean test -Denv=${{ github.event.inputs.environment }}
